- hosts: all
  become: true
      
  tasks:
      - name: gather ec2 facts
        action: ec2_metadata_facts

      - name: install apache on redhat or centos instances
        yum: name=httpd state=present
        when: ansible_os_family == "RedHat"

      
      - name: enable apache on startup and start service for redhat or centos
        service: name=httpd enabled=yes state=started
        when: ansible_os_family == "RedHat"

      - name: Install git
        yum: name=git state=present

      - name: Git Clone
        git:
          repo: https://github.com/mbettan/maze-oo-new.git 
          dest: /var/www/html/ 
          clone: yes 
          update: no
        

      - name: Restart httpd
        service: name=httpd state=restarted

      - name: Show URL
        debug: msg="THE URL FOR YOUR APPLICATION IS http://{{ ec2_public_dns_name }}/index.php"
